package decide.component.requirements;

public enum RequirementType {
	SYSTEM_REQUIREMENT, 
	SYSTEM_COST,
	COMPONENT_REQUIREMENT,
	COMPONENT_COST,
	SYSTEM_OBJECTIVE,
	COMPONENT_OBJECTIVE,
	
	GLOBAL_CONSTRAINT,
	LOCAL_CONSTRAINT;
}